---
- name: Deploy GitHub repo to Apache2
  hosts: all
  become: true
  become_user: ansible
  gather_facts: false

  vars:
    github_url: "https://github.com/seuncaleb/assignment3.git"
    apache_path: "/var/www/html"


  tasks:
    - name: Ensure Apache2 is installed
      package:
        name: apache2
        state: present
      when: ansible_distribution == 'Ubuntu'  

    - name: Ensure httpd is installed
      package:
        name: httpd
        state: present
      when: ansible_distribution == 'CentOS'  

    - name: Clone GitHub repository
      git:
        repo: "{{ github_url }}"
        dest: "{{ apache_path }}"
        version: "main" 

    - name: Set ownership and permissions
      file:
        path: "{{ apache_path }}"
        owner: " ansible  " 
        group: " ansible  " 
        mode: "0755"

    - name: Restart Apache2 service
      service:
        name: apache2
        state: restarted
      when: ansible_distribution == 'Ubuntu'  

    - name: Restart httpd service
      service:
        name: httpd
        state: restarted
      when: ansible_distribution == 'CentOS'  
